baseURL = "https://cultofmetatron.github.io/irrationalpixels/"
languageCode = "en-us"
title = "Irrational Pixels"
theme = "m10c"

[Params]
    description = "Caffine Inspired Ideas"
    author = "Peter de Croos"
    avatar = "dive-pic.jpeg"

[author]
  name = "Peter de Croos"
  homepage = "https://cultofmetatron.github.io/irrationalpixels/"
