baseURL = "//www.irrationalpixels.com/"
languageCode = "en-us"
title = "Tales From The IO.inspect()"
theme = "m10c"
paginate = 20



[menu]
  [[menu.main]]
    identifier = "home"
    name = "Latest"
    url = "/"
    weight = 1




[params]
  name = "Peter de Croos"
  homepage = "//www.irrationalpixels.com/"
  description = "Caffine Inspired Ideas"
  avatar = "dive-pic.jpeg"
  menu_item_separator = " | "



  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/cultofmetatron"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/cultofmetatron"
  [[params.social]]
    icon = "instagram"
    name = "Instagram"
    url = "https://www.instagram.com/cultofmetatron/"
  [[params.social]]
    icon = "linkedin"
    name = "Linked In"
    url = "https://www.linkedin.com/in/peterdecroos/"
