baseURL = "http://example.org/"
languageCode = "en-us"
title = "Irrational Pixels"
theme = "m10c"

[Params]
    description = "Mechanically seperated memes"
    author = "Peter de Croos"
    avatar = "dive-pic.jpeg"

[author]
  name = "vaga"
  homepage = "https://vaga.io"
